# Generated by Django 5.1.5 on 2025-02-08 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier')], help_text='Toggle: Client for adding funds, Supplier for removing funds', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(help_text='Enter the date when the transaction occurred')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
